plugins:
  - '@typescript-eslint'
  - eslint-comments
  - jest
  - promise
  - unicorn
extends:
  - airbnb-typescript
  - plugin:@typescript-eslint/recommended
  - plugin:eslint-comments/recommended
  - plugin:jest/recommended
  - plugin:promise/recommended
  - plugin:unicorn/recommended
  - prettier
  - prettier/@typescript-eslint
settings:
  import/parsers:
    '@typescript-eslint/parser':
    - .ts
    - .tsx
    - .js
  import/resolver:
    typescript: {}
rules:
  unicorn/filename-case: off
  no-prototype-builtins: 0
  import/prefer-default-export: 0
  import/no-default-export: error
  no-use-before-define:
    - error
    -
      functions: false
      classes: true
      variables: true
  '@typescript-eslint/explicit-function-return-type':
    - error
    - 
      allowExpressions: true
      allowTypedFunctionExpressions: true
  '@typescript-eslint/no-explicit-any':
    - off
  '@typescript-eslint/no-use-before-define':
    - error
    -
      functions: false
      classes: true
      variables: true
      typedefs: true
  '@typescript-eslint/indent':
    - 2
    - 2
  unicorn/prevent-abbreviations: 0
parser: "@typescript-eslint/parser"
parserOptions:
  project: ./tsconfig.json
  ecmaVersion: 2019
  sourceType: module
env:
  node: true
  jest: true
  browser: true