name:        'File Changes Action'
description: 'This action can be added, and you will get outputs of all of the files that have changed in your repository for you to use.'
author:      'Bryan Killian <me@trilom.org>'
inputs:
  github-token:
    description: 'The GITHUB_TOKEN secret if necessary'
  github-object:
    description: 'The github object goes here.'
    required: true
outputs:
  files_created:
    description: 'The names of the newly created files'
  files_updated:
    description: 'The names of the updated files'
  files_deleted:
    description: 'The names of the deleted files'
runs:
  using: 'node12'
  main:  'dist/index.js'
branding:
  icon:  'file-text'
  color: 'red'
