name: 'File Changes Action'
description: 'This action can be added, and you will get outputs of all of the files that have changed in your repository for you to use.'
author: 'Bryan Killian <me@trilom.org>'
inputs:
  githubToken:
    description: 'The GITHUB_TOKEN secret if necessary'
    required: false
outputs:
  files_added:
    description: 'The names of the newly created files'
  files_modified:
    description: 'The names of the updated files'
  files_deleted:
    description: 'The names of the deleted files'
runs:
  using: 'node12'
  main:  'dist/index.js'
branding:
  icon:  'file-text'
  color: 'red'
