name: Integration Tests
on:
  issue_comment:
    types: [created]
  schedule:
    - cron: '0 0 * * *'
  pull_request:
    branches: [master]
  push:
    branches: [master]
jobs:
  integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        event_type: ['push', 'pull_request']
        output: ['json', ',', ''' ''', '_<br />&nbsp;&nbsp;_']
        fileOutput: ['json', ',', ''' ''', '_<br />&nbsp;&nbsp;_']
    if: >-
      ( startsWith(github.head_ref, '1.') 
        || startsWith(github.head_ref, '2.')) 
      || 
      contains(github.event.head_commit.message, 'Release merge from')
      ||
      github.event_name == 'schedule'
      ||
      ( github.event_name == 'issue_comment'
        && github.event.issue.pull_request != '' 
        && contains(github.event.comment.body, '/integration') 
        && github.actor == 'trilom')
    steps:
      - uses: actions/checkout@v2
      - run: yarn build
      - uses: ./
        id: file_changes_build_pr
        if: matrix.event_type == 'pull_request'
        with:
          prNumber: 83
          output: ${{ matrix.output }}
          fileOutput: ${{ matrix.fileOutput }}
      - uses: ./
        id: file_changes_build_push
        if: matrix.event_type == 'push'
        with:
          pushBefore: 6ac7697cd1c4f23a08d4d4edbe7dab06b34c58a2
          pushAfter: 4ee1a1a2515f4ac1b90a56aaeb060b97f20c8968
          output: ${{ matrix.output }}
          fileOutput: ${{ matrix.fileOutput }}
      - run: chmod +x test.sh && bash test.sh
        working-directory: .github/actions/integration
        if: success() && matrix.output == 'json'
        env:
          fileOutput: ${{ matrix.fileOutput }}
          output: ${{ matrix.output }}
          files: ${{ format('{0}{1}', toJSON(steps.file_changes_build_pr.outputs.files), toJSON(steps.file_changes_build_push.outputs.files)) }}
          files_modified: ${{ format('{0}{1}', toJSON(steps.file_changes_build_pr.outputs.files_modified), toJSON(steps.file_changes_build_push.outputs.files_modified)) }}
          files_added: ${{ format('{0}{1}', toJSON(steps.file_changes_build_pr.outputs.files_added), toJSON(steps.file_changes_build_push.outputs.files_added)) }}
          files_deleted: ${{ format('{0}{1}', toJSON(steps.file_changes_build_pr.outputs.files_deleted), toJSON(steps.file_changes_build_push.outputs.files_deleted)) }}
      - run: chmod +x test.sh && bash test.sh
        working-directory: .github/actions/integration
        if: success() && matrix.output != 'json'
        env:
          fileOutput: ${{ matrix.fileOutput }}
          output: ${{ matrix.output }}
          files: ${{ format('{0}{1}', steps.file_changes_build_pr.outputs.files, steps.file_changes_build_push.outputs.files ) }}
          files_modified: ${{ format('{0}{1}', steps.file_changes_build_pr.outputs.files_modified, steps.file_changes_build_push.outputs.files ) }}
          files_added: ${{ format('{0}{1}', steps.file_changes_build_pr.outputs.files_added, steps.file_changes_build_push.outputs.files ) }}
          files_deleted: ${{ format('{0}{1}', steps.file_changes_build_pr.outputs.files_deleted, steps.file_changes_build_push.outputs.files ) }}