name: Contribution Workflow
env:
  isFork: ${{ github.event.pull_request.head.repo.full_name != github.repository }}
on: [pull_request]
jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  # make sure we can build
  build:
    name: yarn install && tsc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make run
      - uses: actions/github-script@0.6.0
        if: failure() && contains(env.isFork, 'false')
        with:
          github-token: ${{ secrets.TRILOM_BOT_TOKEN }}
          script: |
            if ('${{ contains(github.event.pull_request.labels.*.name, 'builds') }}' == 'true') {
              github.issues.removeLabel({owner: context.repo.owner, repo: context.repo.repo, issue_number: context.issue.number,
                name: 'builds'
              })
            }
      - uses: actions/github-script@0.6.0
        if: contains(env.isFork, 'false')
        with:
          github-token: ${{ secrets.TRILOM_BOT_TOKEN }}
          script: |
            github.issues.addLabels({owner: context.repo.owner, repo: context.repo.repo, issue_number: context.issue.number,
              labels: ['builds']
            })
  # test with jest
  test:
    name: jest
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - run: make run
      - run: make run COMMAND=test
      - uses: actions/github-script@0.6.0
        if: failure() && contains(env.isFork, 'false')
        with:
          github-token: ${{ secrets.TRILOM_BOT_TOKEN }}
          script: |
            if ('${{ contains(github.event.pull_request.labels.*.name, 'tested') }}' == 'true') {
              github.issues.removeLabel({owner: context.repo.owner, repo: context.repo.repo, issue_number: context.issue.number,
                name: 'tested'
              })
            }
      - uses: actions/github-script@0.6.0
        if: contains(env.isFork, 'false')
        with:
          github-token: ${{ secrets.TRILOM_BOT_TOKEN }}
          script: |
            github.issues.addLabels({owner: context.repo.owner, repo: context.repo.repo, issue_number: context.issue.number,
              labels: ['tested']
            })
  # lint code in github check
  lintdog-fork:
    name: eslintdog (reviewdog)
    runs-on: ubuntu-latest
    needs: build
    if: github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - uses: actions/checkout@v2
      - name: Lint and report
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          eslint_flags: 'src/**/*.ts'
  # lint code and comment back if possible
  lintdog:
    name: eslintdog (reviewdog)
    runs-on: ubuntu-latest
    needs: build
    if: github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - uses: actions/checkout@v2
      - name: Lint and report
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.TRILOM_BOT_TOKEN }}
          reporter: github-pr-review
          eslint_flags: 'src/**/*.ts'
      - uses: actions/github-script@0.6.0
        if: failure()
        with:
          github-token: ${{ secrets.TRILOM_BOT_TOKEN }}
          script: |
            if ('${{ contains(github.event.pull_request.labels.*.name, 'lintdogged') }}' == 'true') {
              github.issues.removeLabel({owner: context.repo.owner, repo: context.repo.repo, issue_number: context.issue.number,
                name: 'lintdogged'
              })
            }
      - uses: actions/github-script@0.6.0
        with:
          github-token: ${{ secrets.TRILOM_BOT_TOKEN }}
          script: |
            github.issues.addLabels({owner: context.repo.owner, repo: context.repo.repo, issue_number: context.issue.number,
              labels: ['lintdogged']
            })
  # format and push code back if not forked branch
  format_check_push:
    name: prettier
    runs-on: ubuntu-latest
    needs: [lintdog, lintdog-fork]
    if: always()
    env:
      GITHUB_TOKEN: ${{ secrets.TRILOM_BOT_TOKEN }}  
    steps:
      - uses: actions/checkout@v2 # checkout for forks
        if: contains(env.isFork, 'true')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
      - uses: actions/checkout@v2 # checkout for PR
        if: contains(env.isFork, 'false')
        with:
          token: ${{ secrets.TRILOM_BOT_TOKEN }}  
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - run: make run
      - run: make run COMMAND=format-check
      - name: make run COMMAND=format and push code if check failed
        if: failure() && github.actor != 'trilom-bot' && contains(env.isFork, 'false')
        env:
          GITHUB_TOKEN: ${{ secrets.TRILOM_BOT_TOKEN }}  
        run: |
          make run COMMAND=format
          sudo make clean
          git config --local user.email "trilom-bot@trailmix.me"
          git config --local user.name "trilom-bot"
          git add -A
          git diff-index --quiet HEAD || git commit -m "Adding format changes 🤖" -a
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:refs/heads/${{ github.head_ref }} && exit 0
      - uses: actions/github-script@0.6.0
        if: failure() && contains(env.isFork, 'false')
        with:
          github-token: ${{ secrets.TRILOM_BOT_TOKEN }}
          script: |
            if ('${{ contains(github.event.pull_request.labels.*.name, 'pretty') }}' == 'true') {
              github.issues.removeLabel({owner: context.repo.owner, repo: context.repo.repo, issue_number: context.issue.number,
                name: 'pretty'
              })
            }
      - uses: actions/github-script@0.6.0
        if: contains(env.isFork, 'false')
        with:
          github-token: ${{ secrets.TRILOM_BOT_TOKEN }}
          script: |
            github.issues.addLabels({owner: context.repo.owner, repo: context.repo.repo, issue_number: context.issue.number,
              labels: ['pretty']
            })
  # semantic release an auto-merged branch to github package repo, npm, github actions
  release:
    name: Release to NPM, Github, Github Actions Marketplace
    runs-on: ubuntu-latest
    needs: [build, test, lintdog, format_check_push]
    if: >
      github.event.pull_request.head.repo.full_name == github.repository
      && (startsWith(github.head_ref, '1.') || startsWith(github.head_ref, '2.'))
      && (github.base_ref == 'master'
        || github.base_ref == 'next'
        || github.base_ref == 'alpha'
        || github.base_ref == 'beta')
    env:
      GITHUB_TOKEN: ${{ secrets.TRILOM_BOT_TOKEN }}
      SEMANTIC_RELEASE_PACKAGE: '@${{ github.repository }}'
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}
          fetch-depth: 0
      - name: semantic-release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          ref: ${{ github.head_ref }}
          semantic_version: 15.14.0
          extra_plugins: |
            @semantic-release/git@7.0.18
            @semantic-release/changelog
            semantic-release-slack-bot
          dry_run: false
      - name: echo release outputs
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo ${{ steps.semantic.outputs.new_release_version }}
          echo ${{ steps.semantic.outputs.new_release_major_version }}
          echo ${{ steps.semantic.outputs.new_release_minor_version }}
          echo ${{ steps.semantic.outputs.new_release_patch_version }}
      - name: Setup Node.js with GitHub Package Registry
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://npm.pkg.github.com'
          scope: trilom
      - name: Publish To GitHub Package Registry
        if: steps.semantic.outputs.new_release_published == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ env.GITHUB_TOKEN }}
      - uses: actions/github-script@0.6.0
        if: failure() && steps.semantic.outputs.new_release_published == 'true'
        with:
          github-token: ${{ secrets.TRILOM_BOT_TOKEN }}
          script: |
            if ('${{ contains(github.event.pull_request.labels.*.name, 'released') }}' == 'true') {
              github.issues.removeLabel({owner: context.repo.owner, repo: context.repo.repo, issue_number: context.issue.number,
                name: 'released'
              })
            }
      - uses: actions/github-script@0.6.0
        if: steps.semantic.outputs.new_release_published == 'true'
        with:
          github-token: ${{ secrets.TRILOM_BOT_TOKEN }}
          script: |
            github.issues.addLabels({owner: context.repo.owner, repo: context.repo.repo, issue_number: context.issue.number,
              labels: ['released']
            })