# if a pr is made into master and any further pushes(syncronize)
# this will run prettier every run and auto-commit back the code
# then we will lint and report back any issues
name: Format and lint reviewdog
on: 
  pull_request:
    # TODO: CHANGE TO MASTER BRANCH
    branches:
      - develop
jobs:
  format_check_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build code
      run: make run
    - name: Run prettier --check on code
      run: make run COMMAND=format-check
    - name: Format code
      if: failure()
      run: |
        make run COMMAND=format
    - name: Commit files
      if: failure()
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action - Format"
        git commit -m "Add format changes" -a  
  lint_reviewdog:
    name: Run eslint and report to PR
    runs-on: ubuntu-latest
    needs: format_check_push
    steps:
      - uses: actions/checkout@v2
      - name: Lint code
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          eslint_flags: 'src/**/*.ts'