# every week at 5PM GMT run a release test
# on push to release run a release test 
name: Semantic-release test
on:
  push:
    # TODO: CHANGE TO releases/v1
    branches:
      - test/v1
  schedule:
    - cron: 0 17 * * *
jobs:
  test:
    name: Test fake release on releases branch
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # TODO: CHANGE TO releases/v1 BRANCH
    if: github.actor == 'trilom-bot'
    steps:
      - uses: actions/checkout@v2
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          # TODO: CHANGE TO releases/v1 BRANCH
          branch: test/v1
          extra_plugins: |
            @semantic-release/git
            @semantic-release/changelog
          dry_run: true
      - name: Test Outputs
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo ${{ steps.semantic.outputs.new_release_version }}
          echo ${{ steps.semantic.outputs.new_release_major_version }}
          echo ${{ steps.semantic.outputs.new_release_minor_version }}
          echo ${{ steps.semantic.outputs.new_release_patch_version }}